inherit_from: .rubocop_todo.yml

require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - examples/**/*
    - vendor/**/*
    - gemfiles/vendor/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "spec/**/*_spec.rb"

Metrics/ParameterLists:
  Max: 8
  Exclude:
    - "lib/nylas-legacy/calendar_collection.rb"

Metrics/MethodLength:
  Exclude:
    - "lib/nylas-legacy/calendar_collection.rb"
    - "lib/nylas-legacy/services/tunnel.rb"

Metrics/AbcSize:
  Exclude:
    - "lib/nylas-legacy/services/tunnel.rb"

Metrics/ModuleLength:
  Exclude:
    - "lib/nylas-legacy/model.rb"

Naming/FileName:
  Exclude:
    - "lib/nylas-legacy-streaming.rb"

Metrics/ClassLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
